[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Functions configuration
[functions]
  # Directory for serverless functions
  directory = "netlify/functions"
  # Node bundler
  node_bundler = "esbuild"

# Background function configuration
[functions."process-matches-background"]
  # Background functions can run up to 15 minutes on free tier!
  included_files = ["node_modules/**"]
