import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import * as XLSX from 'xlsx';
import { intelligentlyMapRow } from '@/lib/utils/intelligentColumnMapper';
import { aiParseClient } from '@/lib/utils/aiExcelParser';

/**
 * API Route: Upload Clients from Excel (Mistral AI-Powered)
 * POST /api/upload/clients
 *
 * Accepts an Excel file and imports clients into the database
 * Uses Mistral 7B AI model to intelligently parse and map data to correct fields
 * Falls back to regex-based parsing if AI is unavailable
 */
export async function POST(request: NextRequest) {
  try {
    console.log('📤 Starting client bulk upload...');

    // Get form data with file
    const formData = await request.formData();
    const file = formData.get('file') as File;

    if (!file) {
      return NextResponse.json(
        { success: false, error: 'No file uploaded' },
        { status: 400 }
      );
    }

    console.log(`📄 Processing file: ${file.name} (${file.size} bytes)`);

    // Convert file to buffer
    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);

    // Parse Excel or CSV file
    // xlsx library handles both .xlsx, .xls, and .csv files
    const workbook = XLSX.read(buffer, { type: 'buffer', raw: true });
    const sheetName = workbook.SheetNames[0];
    const worksheet = workbook.Sheets[sheetName];
    const jsonData = XLSX.utils.sheet_to_json(worksheet);

    console.log(`📊 Found ${jsonData.length} rows in Excel file`);

    if (jsonData.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Excel file is empty' },
        { status: 400 }
      );
    }

    // Create Supabase client with auth
    const cookieStore = await cookies();
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll();
          },
          setAll(cookiesToSet) {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            );
          },
        },
      }
    );

    // Get authenticated user
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json(
        { success: false, error: 'You must be logged in to upload clients' },
        { status: 401 }
      );
    }

    console.log(`✅ Authenticated user: ${user.email}`);

    // Validate and transform data using Mistral AI (with fallback)
    const clients = [];
    const errors = [];

    // Check if AI is available
    const useAI = process.env.VPS_AI_URL && process.env.VPS_AI_SECRET;

    console.log(`🤖 Using ${useAI ? 'Mistral 7B AI' : 'Regex-based'} intelligent parsing...`);

    for (let i = 0; i < jsonData.length; i++) {
      const row: any = jsonData[i];
      const rowNum = i + 2; // Excel row number (1-indexed + header)

      try {
        // Check if row is completely empty
        const hasAnyData = Object.values(row).some(val => val !== null && val !== undefined && String(val).trim() !== '');
        if (!hasAnyData) {
          continue; // Skip empty rows silently
        }

        console.log(`\n📋 Processing row ${rowNum}:`, row);

        let mapped;

        // Try AI parsing first if available
        if (useAI) {
          try {
            console.log('🤖 Using Mistral AI for parsing...');
            mapped = await aiParseClient(row);
          } catch (aiError) {
            console.warn('⚠️ AI parsing failed, falling back to regex:', aiError);
            mapped = intelligentlyMapRow(row);
          }
        } else {
          // Fallback to regex-based parsing
          console.log('🔧 Using regex-based parsing...');
          mapped = intelligentlyMapRow(row);
        }

        console.log(`✨ Parsed result:`, mapped);

        // ✅ FLEXIBLE UPLOAD: Accept everything, flag issues as warnings
        // The grid UI will show red flags for missing/invalid postcode or role
        const warnings: string[] = [];

        if (!mapped.postcode || mapped.postcode.trim() === '') {
          warnings.push('missing Postcode (will be flagged in grid)');
        }

        if (!mapped.role || mapped.role.trim() === '') {
          warnings.push('missing Role (will be flagged in grid)');
        }

        // Log warnings but don't block upload
        if (warnings.length > 0) {
          console.log(`⚠️ Row ${rowNum}: ${warnings.join(', ')}`);
        }

        const role = mapped.role?.trim() || ''; // Allow empty role

        // Create client object from AI/regex-mapped data
        // AI parser returns client-specific fields, regex parser uses generic fields
        // ID is auto-generated by database, NOT by this code
        const client = {
          surgery: (mapped as any).surgery || mapped.first_name || 'Unnamed Practice',
          client_name: (mapped as any).client_name || mapped.last_name || null,
          client_phone: (mapped as any).client_phone || mapped.phone || null,
          client_email: (mapped as any).client_email || mapped.email || null,
          role: role || '', // Allow empty - will be flagged in UI
          postcode: mapped.postcode ? mapped.postcode.toUpperCase() : '', // Allow empty - will be flagged in UI
          budget: (mapped as any).budget || mapped.salary || null,
          requirement: (mapped as any).requirement || mapped.days || null,
          system: (mapped as any).system || mapped.experience || null,
          notes: mapped.notes || null,
          user_id: user.id,
          added_at: new Date().toISOString()
        };

        console.log(`✅ Final client object:`, client);

        clients.push(client);
      } catch (error) {
        console.error(`❌ Error processing row ${rowNum}:`, error);
        errors.push(`Row ${rowNum}: ${error instanceof Error ? error.message : 'Invalid data'}`);
      }
    }

    console.log(`✅ Validated ${clients.length} clients`);
    if (errors.length > 0) {
      console.log(`⚠️  ${errors.length} validation errors`);
    }

    // Insert clients into database
    // IDs are auto-generated by database
    if (clients.length > 0) {
      const { data: insertedClients, error } = await supabase
        .from('clients')
        .insert(clients)
        .select();

      if (error) {
        console.error('Database insertion error:', error);
        return NextResponse.json(
          {
            success: false,
            error: `Database error: ${error.message}`,
            validationErrors: errors
          },
          { status: 500 }
        );
      }

      console.log(`✅ Successfully inserted ${clients.length} clients`);

      // ✅ NOTES INTEGRATION: Save notes to client_notes table
      if (insertedClients && insertedClients.length > 0) {
        const notesToInsert = [];

        for (let i = 0; i < insertedClients.length; i++) {
          const insertedClient = insertedClients[i];
          const originalClient = clients[i];

          // Check if this client has notes
          if (originalClient.notes && originalClient.notes.trim() !== '') {
            notesToInsert.push({
              client_id: insertedClient.id,
              user_id: user.id,
              content: originalClient.notes.trim(),
            });
          }
        }

        // Insert all notes in batch
        if (notesToInsert.length > 0) {
          const { error: notesError } = await supabase
            .from('client_notes')
            .insert(notesToInsert);

          if (notesError) {
            console.error('⚠️ Error inserting notes:', notesError);
            // Don't fail the whole upload if notes fail - just log warning
          } else {
            console.log(`✅ Successfully saved ${notesToInsert.length} notes`);
          }
        }
      }
    }

    // Always return success with stats (flexible upload - no blocking validation)
    const response: any = {
      success: clients.length > 0,
      message: clients.length > 0
        ? `Successfully uploaded ${clients.length} client(s). ${clients.length < jsonData.length ? 'Check grid for any rows with missing Postcode/Role - they will be highlighted in red.' : ''}`
        : 'No clients found in file. Please check that your file contains data rows.',
      stats: {
        total_rows: jsonData.length,
        successful: clients.length,
        errors: errors.length
      }
    };

    // Only show errors for actual parsing failures (not validation warnings)
    if (errors.length > 0) {
      response.validationErrors = errors;
    }

    return NextResponse.json(response);

  } catch (error) {
    console.error('Client upload error:', error);
    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to upload clients'
      },
      { status: 500 }
    );
  }
}
